# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resourcesFile/GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1680, 950)
        MainWindow.setStyleSheet("QMainWindow{\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenu = QtWidgets.QWidget(self.centralwidget)
        self.leftMenu.setMinimumSize(QtCore.QSize(152, 0))
        self.leftMenu.setMaximumSize(QtCore.QSize(152, 16777215))
        self.leftMenu.setStyleSheet("background-color: rgb(14, 203, 255);\n"
"\n"
"border-top-right-radius : 15px; \n"
"border-bottom-right-radius : 15px;\n"
"")
        self.leftMenu.setObjectName("leftMenu")
        self.layoutWidget = QtWidgets.QWidget(self.leftMenu)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 127, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.configButton = QtWidgets.QPushButton(self.layoutWidget)
        self.configButton.setMinimumSize(QtCore.QSize(0, 28))
        self.configButton.setMaximumSize(QtCore.QSize(151, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.configButton.setFont(font)
        self.configButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(206, 206, 206);\n"
"}")
        self.configButton.setObjectName("configButton")
        self.verticalLayout.addWidget(self.configButton)
        self.viewButton = QtWidgets.QPushButton(self.layoutWidget)
        self.viewButton.setMinimumSize(QtCore.QSize(0, 28))
        self.viewButton.setMaximumSize(QtCore.QSize(151, 16777215))
        self.viewButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(206, 206, 206);\n"
"}")
        self.viewButton.setObjectName("viewButton")
        self.verticalLayout.addWidget(self.viewButton)
        self.chipViewButton = QtWidgets.QPushButton(self.layoutWidget)
        self.chipViewButton.setMinimumSize(QtCore.QSize(0, 28))
        self.chipViewButton.setMaximumSize(QtCore.QSize(151, 16777215))
        self.chipViewButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(206, 206, 206);\n"
"}")
        self.chipViewButton.setObjectName("chipViewButton")
        self.verticalLayout.addWidget(self.chipViewButton)
        self.horizontalLayout.addWidget(self.leftMenu)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(890, 0))
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"background-color: rgb(245, 245, 245);\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(-5, 0, 1750, 850))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_3.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_3.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.formLayout_7 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_3)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setSpacing(0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.main = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setMinimumSize(QtCore.QSize(1750, 850))
        self.main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.main.setFont(font)
        self.main.setStyleSheet("QStackedWidget{\n"
"    background-color: rgb(245, 245, 245);\n"
"}")
        self.main.setObjectName("main")
        self.configPage = QtWidgets.QWidget()
        self.configPage.setObjectName("configPage")
        self.frame = QtWidgets.QFrame(self.configPage)
        self.frame.setGeometry(QtCore.QRect(640, 30, 701, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("font: 75 12pt \"8514oem\";")
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.frame1 = QtWidgets.QFrame(self.frame)
        self.frame1.setStyleSheet(".QFrame{\n"
"background-color: rgb(214, 214, 214);\n"
"border-radius:15px;\n"
"}")
        self.frame1.setObjectName("frame1")
        self.formLayout = QtWidgets.QFormLayout(self.frame1)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_27 = QtWidgets.QLabel(self.frame1)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_19.addWidget(self.label_27)
        self.stropeLampOption = QtWidgets.QComboBox(self.frame1)
        self.stropeLampOption.setMinimumSize(QtCore.QSize(53, 30))
        self.stropeLampOption.setStyleSheet("QComboBox::indicator{\n"
"    background-color: rgb(255, 255, 255);\n"
"    selection-background-color:rgb(255, 255, 255);\n"
"    color:rgb(255, 255, 255);\n"
"    selection-color:transparent;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.stropeLampOption.setObjectName("stropeLampOption")
        self.stropeLampOption.addItem("")
        self.stropeLampOption.addItem("")
        self.horizontalLayout_19.addWidget(self.stropeLampOption)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_28 = QtWidgets.QLabel(self.frame1)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_20.addWidget(self.label_28)
        self.stropeLampMode = QtWidgets.QComboBox(self.frame1)
        self.stropeLampMode.setMinimumSize(QtCore.QSize(53, 30))
        self.stropeLampMode.setStyleSheet("QComboBox::indicator{\n"
"    background-color: transparent;\n"
"    selection-background-color:transparent;\n"
"    color:transparent;\n"
"    selection-color:transparent;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.stropeLampMode.setObjectName("stropeLampMode")
        self.stropeLampMode.addItem("")
        self.stropeLampMode.addItem("")
        self.horizontalLayout_20.addWidget(self.stropeLampMode)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_29 = QtWidgets.QLabel(self.frame1)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_21.addWidget(self.label_29)
        self.strobeLampPeriod = QtWidgets.QLineEdit(self.frame1)
        self.strobeLampPeriod.setMinimumSize(QtCore.QSize(118, 28))
        self.strobeLampPeriod.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.strobeLampPeriod.setObjectName("strobeLampPeriod")
        self.horizontalLayout_21.addWidget(self.strobeLampPeriod)
        self.periodUnit = QtWidgets.QComboBox(self.frame1)
        self.periodUnit.setMinimumSize(QtCore.QSize(100, 28))
        self.periodUnit.setStyleSheet("")
        self.periodUnit.setObjectName("periodUnit")
        self.periodUnit.addItem("")
        self.periodUnit.addItem("")
        self.horizontalLayout_21.addWidget(self.periodUnit)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_21)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_18)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(7)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(5)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_25 = QtWidgets.QLabel(self.frame1)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_16.addWidget(self.label_25)
        self.integrationTime = customLineEdit(self.frame1)
        self.integrationTime.setMinimumSize(QtCore.QSize(118, 28))
        self.integrationTime.setMaximumSize(QtCore.QSize(120, 16777215))
        self.integrationTime.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.integrationTime.setObjectName("integrationTime")
        self.horizontalLayout_16.addWidget(self.integrationTime)
        self.integrationTimeUnit = QtWidgets.QComboBox(self.frame1)
        self.integrationTimeUnit.setMinimumSize(QtCore.QSize(100, 28))
        self.integrationTimeUnit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.integrationTimeUnit.setObjectName("integrationTimeUnit")
        self.integrationTimeUnit.addItem("")
        self.integrationTimeUnit.addItem("")
        self.horizontalLayout_16.addWidget(self.integrationTimeUnit)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(5)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_26 = QtWidgets.QLabel(self.frame1)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_17.addWidget(self.label_26)
        self.triggerMode = QtWidgets.QComboBox(self.frame1)
        self.triggerMode.setMinimumSize(QtCore.QSize(147, 30))
        self.triggerMode.setStyleSheet("QComboBox::indicator{\n"
"    background-color: transparent;\n"
"    selection-background-color:transparent;\n"
"    color:transparent;\n"
"    selection-color:transparent;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.triggerMode.setObjectName("triggerMode")
        self.triggerMode.addItem("")
        self.triggerMode.addItem("")
        self.triggerMode.addItem("")
        self.triggerMode.addItem("")
        self.horizontalLayout_17.addWidget(self.triggerMode)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_17)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_15)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.frame1)
        self.frame2 = QtWidgets.QFrame(self.configPage)
        self.frame2.setGeometry(QtCore.QRect(640, 190, 391, 221))
        self.frame2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame2.setObjectName("frame2")
        self.formLayout_5 = QtWidgets.QFormLayout(self.frame2)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame2)
        self.label_4.setStyleSheet("font: 75 12pt \"8514oem\";")
        self.label_4.setObjectName("label_4")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.frame3 = QtWidgets.QFrame(self.frame2)
        self.frame3.setMinimumSize(QtCore.QSize(0, 85))
        self.frame3.setStyleSheet(".QFrame{\n"
"background-color: rgb(214, 214, 214);\n"
"border-radius:15px;\n"
"}")
        self.frame3.setObjectName("frame3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame3)
        self.formLayout_4.setObjectName("formLayout_4")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_30 = QtWidgets.QLabel(self.frame3)
        self.label_30.setMinimumSize(QtCore.QSize(114, 0))
        self.label_30.setMaximumSize(QtCore.QSize(114, 16777215))
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_22.addWidget(self.label_30)
        self.dropletTravelTime = customLineEdit(self.frame3)
        self.dropletTravelTime.setMinimumSize(QtCore.QSize(75, 28))
        self.dropletTravelTime.setMaximumSize(QtCore.QSize(75, 16777215))
        self.dropletTravelTime.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.dropletTravelTime.setObjectName("dropletTravelTime")
        self.horizontalLayout_22.addWidget(self.dropletTravelTime)
        self.dropletTravelTimeUnit = QtWidgets.QComboBox(self.frame3)
        self.dropletTravelTimeUnit.setMinimumSize(QtCore.QSize(120, 28))
        self.dropletTravelTimeUnit.setObjectName("dropletTravelTimeUnit")
        self.dropletTravelTimeUnit.addItem("")
        self.dropletTravelTimeUnit.addItem("")
        self.horizontalLayout_22.addWidget(self.dropletTravelTimeUnit)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_31 = QtWidgets.QLabel(self.frame3)
        self.label_31.setMinimumSize(QtCore.QSize(114, 0))
        self.label_31.setMaximumSize(QtCore.QSize(114, 16777215))
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_23.addWidget(self.label_31)
        self.pulseTime = customLineEdit(self.frame3)
        self.pulseTime.setMinimumSize(QtCore.QSize(75, 28))
        self.pulseTime.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pulseTime.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.pulseTime.setObjectName("pulseTime")
        self.horizontalLayout_23.addWidget(self.pulseTime)
        self.pulseTimeUnit = QtWidgets.QComboBox(self.frame3)
        self.pulseTimeUnit.setMinimumSize(QtCore.QSize(120, 28))
        self.pulseTimeUnit.setObjectName("pulseTimeUnit")
        self.pulseTimeUnit.addItem("")
        self.pulseTimeUnit.addItem("")
        self.horizontalLayout_23.addWidget(self.pulseTimeUnit)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_32 = QtWidgets.QLabel(self.frame3)
        self.label_32.setMinimumSize(QtCore.QSize(114, 0))
        self.label_32.setMaximumSize(QtCore.QSize(114, 16777215))
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_24.addWidget(self.label_32)
        self.numberOfDroplet = customLineEdit(self.frame3)
        self.numberOfDroplet.setMinimumSize(QtCore.QSize(75, 28))
        self.numberOfDroplet.setMaximumSize(QtCore.QSize(75, 16777215))
        self.numberOfDroplet.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.numberOfDroplet.setObjectName("numberOfDroplet")
        self.horizontalLayout_24.addWidget(self.numberOfDroplet)
        self.numberOfDropletUnit = QtWidgets.QComboBox(self.frame3)
        self.numberOfDropletUnit.setMinimumSize(QtCore.QSize(120, 28))
        self.numberOfDropletUnit.setObjectName("numberOfDropletUnit")
        self.numberOfDropletUnit.addItem("")
        self.numberOfDropletUnit.addItem("")
        self.horizontalLayout_24.addWidget(self.numberOfDropletUnit)
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_24)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_33 = QtWidgets.QLabel(self.frame3)
        self.label_33.setMinimumSize(QtCore.QSize(114, 0))
        self.label_33.setMaximumSize(QtCore.QSize(114, 16777215))
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_26.addWidget(self.label_33)
        self.sortingElectrode = customLineEdit(self.frame3)
        self.sortingElectrode.setMinimumSize(QtCore.QSize(75, 28))
        self.sortingElectrode.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sortingElectrode.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.sortingElectrode.setObjectName("sortingElectrode")
        self.horizontalLayout_26.addWidget(self.sortingElectrode)
        self.formLayout_4.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_26)
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.frame3)
        self.frame4 = QtWidgets.QFrame(self.configPage)
        self.frame4.setGeometry(QtCore.QRect(20, 340, 601, 441))
        self.frame4.setStyleSheet("")
        self.frame4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame4.setLineWidth(1)
        self.frame4.setMidLineWidth(0)
        self.frame4.setObjectName("frame4")
        self.formLayout_6 = QtWidgets.QFormLayout(self.frame4)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame4)
        self.label_2.setStyleSheet("font: 75 12pt \"8514oem\";")
        self.label_2.setObjectName("label_2")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.nemCheckBox = QtWidgets.QCheckBox(self.frame4)
        self.nemCheckBox.setObjectName("nemCheckBox")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nemCheckBox)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.nemDeletePath = QtWidgets.QToolButton(self.frame4)
        self.nemDeletePath.setMinimumSize(QtCore.QSize(27, 22))
        self.nemDeletePath.setMaximumSize(QtCore.QSize(27, 22))
        self.nemDeletePath.setStyleSheet("image:url(:/Icons/deleteFolder.png);\n"
"background-color: rgb(255, 255, 255);")
        self.nemDeletePath.setText("")
        self.nemDeletePath.setObjectName("nemDeletePath")
        self.horizontalLayout_8.addWidget(self.nemDeletePath)
        self.nemAddPath = QtWidgets.QToolButton(self.frame4)
        self.nemAddPath.setMinimumSize(QtCore.QSize(27, 22))
        self.nemAddPath.setMaximumSize(QtCore.QSize(27, 22))
        self.nemAddPath.setStyleSheet("image:url(:/Icons/addFolder.png);\n"
"background-color: rgb(255, 255, 255);")
        self.nemAddPath.setText("")
        self.nemAddPath.setObjectName("nemAddPath")
        self.horizontalLayout_8.addWidget(self.nemAddPath)
        self.nemPropertyPath = QtWidgets.QComboBox(self.frame4)
        self.nemPropertyPath.setMinimumSize(QtCore.QSize(381, 21))
        self.nemPropertyPath.setMaximumSize(QtCore.QSize(381, 21))
        self.nemPropertyPath.setObjectName("nemPropertyPath")
        self.horizontalLayout_8.addWidget(self.nemPropertyPath)
        self.formLayout_6.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_8)
        self.pumpScrollArea = QtWidgets.QScrollArea(self.frame4)
        self.pumpScrollArea.setMinimumSize(QtCore.QSize(0, 242))
        self.pumpScrollArea.setWidgetResizable(True)
        self.pumpScrollArea.setObjectName("pumpScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 573, 240))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pumpName = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.pumpName.setMinimumSize(QtCore.QSize(80, 30))
        self.pumpName.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pumpName.setFont(font)
        self.pumpName.setObjectName("pumpName")
        self.horizontalLayout_7.addWidget(self.pumpName)
        self.SyringeDiameter = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.SyringeDiameter.setMinimumSize(QtCore.QSize(115, 30))
        self.SyringeDiameter.setMaximumSize(QtCore.QSize(115, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SyringeDiameter.setFont(font)
        self.SyringeDiameter.setObjectName("SyringeDiameter")
        self.horizontalLayout_7.addWidget(self.SyringeDiameter)
        self.SyringeStroke = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.SyringeStroke.setMinimumSize(QtCore.QSize(115, 30))
        self.SyringeStroke.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SyringeStroke.setFont(font)
        self.SyringeStroke.setObjectName("SyringeStroke")
        self.horizontalLayout_7.addWidget(self.SyringeStroke)
        self.pumpStatus = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.pumpStatus.setMinimumSize(QtCore.QSize(60, 30))
        self.pumpStatus.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pumpStatus.setFont(font)
        self.pumpStatus.setObjectName("pumpStatus")
        self.horizontalLayout_7.addWidget(self.pumpStatus)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.pumpScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.pumpScrollArea)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.pumpCalibrationInput = QtWidgets.QLineEdit(self.frame4)
        self.pumpCalibrationInput.setMinimumSize(QtCore.QSize(75, 0))
        self.pumpCalibrationInput.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pumpCalibrationInput.setStyleSheet("padding: 4px;\n"
"")
        self.pumpCalibrationInput.setText("")
        self.pumpCalibrationInput.setObjectName("pumpCalibrationInput")
        self.horizontalLayout_10.addWidget(self.pumpCalibrationInput)
        self.calibrateButton = QtWidgets.QPushButton(self.frame4)
        self.calibrateButton.setMinimumSize(QtCore.QSize(110, 0))
        self.calibrateButton.setMaximumSize(QtCore.QSize(157, 16777215))
        self.calibrateButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(206, 206, 206);\n"
"}")
        self.calibrateButton.setObjectName("calibrateButton")
        self.horizontalLayout_10.addWidget(self.calibrateButton)
        self.formLayout_6.setLayout(5, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_10)
        self.pumpConnectButton = QtWidgets.QPushButton(self.frame4)
        self.pumpConnectButton.setMaximumSize(QtCore.QSize(151, 16777215))
        self.pumpConnectButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(206, 206, 206);\n"
"}")
        self.pumpConnectButton.setObjectName("pumpConnectButton")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pumpConnectButton)
        self.frame5 = QtWidgets.QFrame(self.frame4)
        self.frame5.setObjectName("frame5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame5)
        self.horizontalLayout_9.setSpacing(7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.frame5)
        self.label_3.setMinimumSize(QtCore.QSize(20, 21))
        self.label_3.setMaximumSize(QtCore.QSize(200, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.busStatus = QtWidgets.QLabel(self.frame5)
        self.busStatus.setText("")
        self.busStatus.setObjectName("busStatus")
        self.horizontalLayout_9.addWidget(self.busStatus)
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.frame5)
        self.frame6 = QtWidgets.QFrame(self.configPage)
        self.frame6.setGeometry(QtCore.QRect(20, 30, 601, 291))
        self.frame6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame6.setObjectName("frame6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.frame6)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setStyleSheet("font: 75 12pt \"8514oem\";")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 3)
        self.label_34 = QtWidgets.QLabel(self.frame6)
        self.label_34.setMinimumSize(QtCore.QSize(0, 28))
        self.label_34.setMaximumSize(QtCore.QSize(45, 30))
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 1, 0, 1, 1)
        self.deviceConnectButton = QtWidgets.QPushButton(self.frame6)
        self.deviceConnectButton.setMinimumSize(QtCore.QSize(80, 0))
        self.deviceConnectButton.setMaximumSize(QtCore.QSize(111, 28))
        self.deviceConnectButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(206, 206, 206);\n"
"}")
        self.deviceConnectButton.setObjectName("deviceConnectButton")
        self.gridLayout_2.addWidget(self.deviceConnectButton, 1, 2, 1, 1)
        self.deviceList = QtWidgets.QComboBox(self.frame6)
        self.deviceList.setMinimumSize(QtCore.QSize(0, 28))
        self.deviceList.setMaximumSize(QtCore.QSize(381, 28))
        self.deviceList.setObjectName("deviceList")
        self.gridLayout_2.addWidget(self.deviceList, 1, 1, 1, 1)
        self.hardwareTextBox = QtWidgets.QPlainTextEdit(self.frame6)
        self.hardwareTextBox.setMaximumSize(QtCore.QSize(16777215, 200))
        self.hardwareTextBox.setObjectName("hardwareTextBox")
        self.gridLayout_2.addWidget(self.hardwareTextBox, 4, 0, 1, 4)
        self.sendParamButtom = QtWidgets.QPushButton(self.frame6)
        self.sendParamButtom.setMinimumSize(QtCore.QSize(80, 0))
        self.sendParamButtom.setMaximumSize(QtCore.QSize(111, 28))
        self.sendParamButtom.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(206, 206, 206);\n"
"}")
        self.sendParamButtom.setObjectName("sendParamButtom")
        self.gridLayout_2.addWidget(self.sendParamButtom, 1, 3, 1, 1)
        self.frame7 = QtWidgets.QFrame(self.configPage)
        self.frame7.setGeometry(QtCore.QRect(640, 450, 391, 191))
        self.frame7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame7.setObjectName("frame7")
        self.formLayout_9 = QtWidgets.QFormLayout(self.frame7)
        self.formLayout_9.setContentsMargins(11, 11, 11, 11)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_13 = QtWidgets.QLabel(self.frame7)
        self.label_13.setStyleSheet("font: 75 12pt \"8514oem\";")
        self.label_13.setObjectName("label_13")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.frame8 = QtWidgets.QFrame(self.frame7)
        self.frame8.setStyleSheet(".QFrame{\n"
"background-color: rgb(214, 214, 214);\n"
"border-radius:15px;\n"
"}")
        self.frame8.setObjectName("frame8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.frame8)
        self.formLayout_8.setContentsMargins(11, 11, 11, 11)
        self.formLayout_8.setObjectName("formLayout_8")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_35 = QtWidgets.QLabel(self.frame8)
        self.label_35.setMinimumSize(QtCore.QSize(114, 0))
        self.label_35.setMaximumSize(QtCore.QSize(114, 16777215))
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_27.addWidget(self.label_35)
        self.exposureTimeInput = customLineEdit(self.frame8)
        self.exposureTimeInput.setMinimumSize(QtCore.QSize(75, 28))
        self.exposureTimeInput.setMaximumSize(QtCore.QSize(75, 16777215))
        self.exposureTimeInput.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.exposureTimeInput.setObjectName("exposureTimeInput")
        self.horizontalLayout_27.addWidget(self.exposureTimeInput)
        self.dropletTravelTimeUnit_2 = QtWidgets.QComboBox(self.frame8)
        self.dropletTravelTimeUnit_2.setMinimumSize(QtCore.QSize(120, 28))
        self.dropletTravelTimeUnit_2.setObjectName("dropletTravelTimeUnit_2")
        self.dropletTravelTimeUnit_2.addItem("")
        self.horizontalLayout_27.addWidget(self.dropletTravelTimeUnit_2)
        self.formLayout_8.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_36 = QtWidgets.QLabel(self.frame8)
        self.label_36.setMinimumSize(QtCore.QSize(114, 0))
        self.label_36.setMaximumSize(QtCore.QSize(114, 16777215))
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_28.addWidget(self.label_36)
        self.cameraWidth = customLineEdit(self.frame8)
        self.cameraWidth.setMinimumSize(QtCore.QSize(75, 28))
        self.cameraWidth.setMaximumSize(QtCore.QSize(75, 16777215))
        self.cameraWidth.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.cameraWidth.setObjectName("cameraWidth")
        self.horizontalLayout_28.addWidget(self.cameraWidth)
        self.formLayout_8.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_39 = QtWidgets.QLabel(self.frame8)
        self.label_39.setMinimumSize(QtCore.QSize(114, 0))
        self.label_39.setMaximumSize(QtCore.QSize(114, 16777215))
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_29.addWidget(self.label_39)
        self.cameraHeight = customLineEdit(self.frame8)
        self.cameraHeight.setMinimumSize(QtCore.QSize(75, 28))
        self.cameraHeight.setMaximumSize(QtCore.QSize(75, 16777215))
        self.cameraHeight.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.cameraHeight.setObjectName("cameraHeight")
        self.horizontalLayout_29.addWidget(self.cameraHeight)
        self.formLayout_8.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_29)
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.frame8)
        self.main.addWidget(self.configPage)
        self.sortingPage = QtWidgets.QWidget()
        self.sortingPage.setObjectName("sortingPage")
        self.graphWidget = PlotWidget(self.sortingPage)
        self.graphWidget.setGeometry(QtCore.QRect(10, 10, 851, 531))
        self.graphWidget.setObjectName("graphWidget")
        self.frameRate = QtWidgets.QLabel(self.graphWidget)
        self.frameRate.setGeometry(QtCore.QRect(810, 0, 41, 31))
        self.frameRate.setObjectName("frameRate")
        self.layoutWidget1 = QtWidgets.QWidget(self.sortingPage)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 600, 361, 191))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setStyleSheet("font: 75 12pt \"8514oem\";")
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.frame9 = QtWidgets.QFrame(self.layoutWidget1)
        self.frame9.setMinimumSize(QtCore.QSize(350, 0))
        self.frame9.setStyleSheet("QFrame{\n"
"background-color: rgb(214, 214, 214);\n"
"border-radius:15px;\n"
"}")
        self.frame9.setObjectName("frame9")
        self.gridLayout = QtWidgets.QGridLayout(self.frame9)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(10)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_37 = QtWidgets.QLabel(self.frame9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_25.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.frame9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_25.addWidget(self.label_38)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_43 = QtWidgets.QLabel(self.frame9)
        self.label_43.setMinimumSize(QtCore.QSize(74, 0))
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_4.addWidget(self.label_43)
        self.wavelengthMin = customLineEdit(self.frame9)
        self.wavelengthMin.setMinimumSize(QtCore.QSize(100, 0))
        self.wavelengthMin.setMaximumSize(QtCore.QSize(100, 30))
        self.wavelengthMin.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.wavelengthMin.setObjectName("wavelengthMin")
        self.horizontalLayout_4.addWidget(self.wavelengthMin)
        self.wavelengthMax = customLineEdit(self.frame9)
        self.wavelengthMax.setMinimumSize(QtCore.QSize(100, 0))
        self.wavelengthMax.setMaximumSize(QtCore.QSize(100, 30))
        self.wavelengthMax.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.wavelengthMax.setObjectName("wavelengthMax")
        self.horizontalLayout_4.addWidget(self.wavelengthMax)
        self.label_42 = QtWidgets.QLabel(self.frame9)
        self.label_42.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_4.addWidget(self.label_42)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_41 = QtWidgets.QLabel(self.frame9)
        self.label_41.setMinimumSize(QtCore.QSize(74, 0))
        self.label_41.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_3.addWidget(self.label_41)
        self.intensityMin = customLineEdit(self.frame9)
        self.intensityMin.setMinimumSize(QtCore.QSize(100, 0))
        self.intensityMin.setMaximumSize(QtCore.QSize(100, 30))
        self.intensityMin.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.intensityMin.setObjectName("intensityMin")
        self.horizontalLayout_3.addWidget(self.intensityMin)
        self.intensityMax = customLineEdit(self.frame9)
        self.intensityMax.setMinimumSize(QtCore.QSize(100, 0))
        self.intensityMax.setMaximumSize(QtCore.QSize(100, 30))
        self.intensityMax.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.intensityMax.setObjectName("intensityMax")
        self.horizontalLayout_3.addWidget(self.intensityMax)
        self.label_40 = QtWidgets.QLabel(self.frame9)
        self.label_40.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_3.addWidget(self.label_40)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 38, -1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.frame9)
        self.layoutWidget2 = QtWidgets.QWidget(self.sortingPage)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 550, 591, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_45 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_45.setMinimumSize(QtCore.QSize(74, 30))
        self.label_45.setMaximumSize(QtCore.QSize(140, 60))
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_2.addWidget(self.label_45)
        self.spectrometerOptionBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.spectrometerOptionBox.setMinimumSize(QtCore.QSize(0, 30))
        self.spectrometerOptionBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spectrometerOptionBox.setObjectName("spectrometerOptionBox")
        self.horizontalLayout_2.addWidget(self.spectrometerOptionBox)
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget2)
        self.frame_2.setMaximumSize(QtCore.QSize(36, 21))
        self.frame_2.setObjectName("frame_2")
        self.recordBackground = QtWidgets.QLabel(self.frame_2)
        self.recordBackground.setGeometry(QtCore.QRect(0, 0, 36, 21))
        self.recordBackground.setMaximumSize(QtCore.QSize(36, 21))
        self.recordBackground.setStyleSheet("")
        self.recordBackground.setText("")
        self.recordBackground.setObjectName("recordBackground")
        self.spectrometerRecordButton = QtWidgets.QCheckBox(self.frame_2)
        self.spectrometerRecordButton.setGeometry(QtCore.QRect(0, 0, 36, 21))
        self.spectrometerRecordButton.setMaximumSize(QtCore.QSize(37, 22))
        self.spectrometerRecordButton.setStyleSheet("QCheckBox::indicator{\n"
"    width:36px;\n"
"    height:36px;\n"
"    background-color: transparent;\n"
"}\n"
"QCheckBox::indicator::unchecked{\n"
"    image:url(:/Icons/offButton.png);\n"
"}\n"
"QCheckBox::indicator::checked{\n"
"    image:url(:/Icons/onButton.png);\n"
"}")
        self.spectrometerRecordButton.setText("")
        self.spectrometerRecordButton.setObjectName("spectrometerRecordButton")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame10 = QtWidgets.QFrame(self.sortingPage)
        self.frame10.setGeometry(QtCore.QRect(890, 10, 661, 351))
        self.frame10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame10.setObjectName("frame10")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pump4Stop = QtWidgets.QPushButton(self.frame10)
        self.pump4Stop.setObjectName("pump4Stop")
        self.gridLayout_5.addWidget(self.pump4Stop, 9, 5, 1, 1)
        self.pump1Start = QtWidgets.QPushButton(self.frame10)
        self.pump1Start.setObjectName("pump1Start")
        self.gridLayout_5.addWidget(self.pump1Start, 1, 4, 1, 1)
        self.pump4Start = QtWidgets.QPushButton(self.frame10)
        self.pump4Start.setObjectName("pump4Start")
        self.gridLayout_5.addWidget(self.pump4Start, 9, 4, 1, 1)
        self.pump2Stop = QtWidgets.QPushButton(self.frame10)
        self.pump2Stop.setObjectName("pump2Stop")
        self.gridLayout_5.addWidget(self.pump2Stop, 4, 5, 1, 1)
        self.pump2Start = QtWidgets.QPushButton(self.frame10)
        self.pump2Start.setObjectName("pump2Start")
        self.gridLayout_5.addWidget(self.pump2Start, 4, 4, 1, 1)
        self.pump5Stop = QtWidgets.QPushButton(self.frame10)
        self.pump5Stop.setObjectName("pump5Stop")
        self.gridLayout_5.addWidget(self.pump5Stop, 11, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame10)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_15.setStyleSheet("font: 75 12pt \"8514oem\";")
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 1, 1, 5)
        self.pump1Name = QtWidgets.QLineEdit(self.frame10)
        self.pump1Name.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.pump1Name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pump1Name.setText("")
        self.pump1Name.setObjectName("pump1Name")
        self.gridLayout_5.addWidget(self.pump1Name, 1, 1, 1, 1)
        self.pump3Stop = QtWidgets.QPushButton(self.frame10)
        self.pump3Stop.setObjectName("pump3Stop")
        self.gridLayout_5.addWidget(self.pump3Stop, 7, 5, 1, 1)
        self.pump5Start = QtWidgets.QPushButton(self.frame10)
        self.pump5Start.setObjectName("pump5Start")
        self.gridLayout_5.addWidget(self.pump5Start, 11, 4, 1, 1)
        self.pump3Start = QtWidgets.QPushButton(self.frame10)
        self.pump3Start.setObjectName("pump3Start")
        self.gridLayout_5.addWidget(self.pump3Start, 7, 4, 1, 1)
        self.pump2Input = customLineEdit(self.frame10)
        self.pump2Input.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.pump2Input.setObjectName("pump2Input")
        self.gridLayout_5.addWidget(self.pump2Input, 4, 2, 1, 1)
        self.pump1Stop = QtWidgets.QPushButton(self.frame10)
        self.pump1Stop.setObjectName("pump1Stop")
        self.gridLayout_5.addWidget(self.pump1Stop, 1, 5, 1, 1)
        self.pump5Input = customLineEdit(self.frame10)
        self.pump5Input.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.pump5Input.setObjectName("pump5Input")
        self.gridLayout_5.addWidget(self.pump5Input, 11, 2, 1, 1)
        self.pump1Input = customLineEdit(self.frame10)
        self.pump1Input.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.pump1Input.setObjectName("pump1Input")
        self.gridLayout_5.addWidget(self.pump1Input, 1, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame10)
        self.label_18.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 2, 3, 1, 1)
        self.pump2FlowRate = QtWidgets.QLabel(self.frame10)
        self.pump2FlowRate.setObjectName("pump2FlowRate")
        self.gridLayout_5.addWidget(self.pump2FlowRate, 5, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame10)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 5, 3, 1, 1)
        self.pump3Input = customLineEdit(self.frame10)
        self.pump3Input.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.pump3Input.setObjectName("pump3Input")
        self.gridLayout_5.addWidget(self.pump3Input, 7, 2, 1, 1)
        self.pump5FlowRate = QtWidgets.QLabel(self.frame10)
        self.pump5FlowRate.setObjectName("pump5FlowRate")
        self.gridLayout_5.addWidget(self.pump5FlowRate, 12, 2, 1, 1)
        self.pump4Input = customLineEdit(self.frame10)
        self.pump4Input.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.pump4Input.setObjectName("pump4Input")
        self.gridLayout_5.addWidget(self.pump4Input, 9, 2, 1, 1)
        self.pump3FlowRate = QtWidgets.QLabel(self.frame10)
        self.pump3FlowRate.setObjectName("pump3FlowRate")
        self.gridLayout_5.addWidget(self.pump3FlowRate, 8, 2, 1, 1)
        self.pump4FlowRate = QtWidgets.QLabel(self.frame10)
        self.pump4FlowRate.setObjectName("pump4FlowRate")
        self.gridLayout_5.addWidget(self.pump4FlowRate, 10, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame10)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 8, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 5, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame10)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 10, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame10)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 12, 3, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.frame10)
        self.label_44.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 1, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 12, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 8, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 10, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.frame10)
        self.label_47.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 7, 3, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.frame10)
        self.label_48.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.label_48, 9, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.frame10)
        self.label_46.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 4, 3, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.frame10)
        self.label_49.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_49.setObjectName("label_49")
        self.gridLayout_5.addWidget(self.label_49, 11, 3, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.frame10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_5.addWidget(self.label_50, 9, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 7, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame10)
        self.label_8.setMinimumSize(QtCore.QSize(67, 0))
        self.label_8.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 11, 0, 1, 1)
        self.pump1FlowRate = QtWidgets.QLabel(self.frame10)
        self.pump1FlowRate.setMinimumSize(QtCore.QSize(25, 0))
        self.pump1FlowRate.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pump1FlowRate.setObjectName("pump1FlowRate")
        self.gridLayout_5.addWidget(self.pump1FlowRate, 2, 2, 1, 1)
        self.pump2Name = QtWidgets.QLineEdit(self.frame10)
        self.pump2Name.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.pump2Name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pump2Name.setText("")
        self.pump2Name.setObjectName("pump2Name")
        self.gridLayout_5.addWidget(self.pump2Name, 4, 1, 1, 1)
        self.pump5Name = QtWidgets.QLineEdit(self.frame10)
        self.pump5Name.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.pump5Name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pump5Name.setText("")
        self.pump5Name.setObjectName("pump5Name")
        self.gridLayout_5.addWidget(self.pump5Name, 11, 1, 1, 1)
        self.pump4Name = QtWidgets.QLineEdit(self.frame10)
        self.pump4Name.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.pump4Name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pump4Name.setText("")
        self.pump4Name.setObjectName("pump4Name")
        self.gridLayout_5.addWidget(self.pump4Name, 9, 1, 1, 1)
        self.pump3Name = QtWidgets.QLineEdit(self.frame10)
        self.pump3Name.setStyleSheet("padding: 6px;\n"
"border-top-left-radius :10px;\n"
"border-top-right-radius : 10px; \n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.pump3Name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pump3Name.setText("")
        self.pump3Name.setObjectName("pump3Name")
        self.gridLayout_5.addWidget(self.pump3Name, 7, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 2, 1, 1, 1)
        self.main.addWidget(self.sortingPage)
        self.chipViewerPage = QtWidgets.QWidget()
        self.chipViewerPage.setObjectName("chipViewerPage")
        self.chipViewer = customGraphicView(self.chipViewerPage)
        # self.chipViewer.setGeometry(QtCore.QRect(10, 10, 961, 671))
        self.chipViewer.setObjectName("chipViewer")

        self.layout1 = QtWidgets.QHBoxLayout()
        self.layout1.setAlignment(QtCore.Qt.AlignLeft)
        self.layout2 = QtWidgets.QVBoxLayout()
        self.chipViewerPage.setLayout(self.layout1)
        self.chipViewer.setMaximumWidth(1300)
        self.chipViewer.setGeometry(QtCore.QRect(0, 0, 600, 671))
        self.listWidget = QtWidgets.QListWidget()
        self.listWidget.setMaximumSize(300,166667)
        self.listWidget.setDragEnabled(True)
        QtWidgets.QListWidgetItem("Electrode", self.listWidget)
        self.elecTrodeLabel = QtWidgets.QLabel("Enter Electrode Number")
        self.electrodePulseTimeLabel = QtWidgets.QLabel("Pulse Time (us)")
        self.clearAllButton = QtWidgets.QPushButton("Clear All")
        self.loadButton = QtWidgets.QPushButton("Load")
        self.saveAsButton = QtWidgets.QPushButton("Save As")
        self.electroNumberInput = QtWidgets.QLineEdit()
        self.electroNumberInput.setMaximumSize(300,100)
        self.electrodePulseTimeInput = QtWidgets.QLineEdit()
        self.electrodePulseTimeInput.setMaximumSize(300,100)
        self.layout2.addWidget(self.clearAllButton)
        self.layout2.addWidget(self.loadButton)
        self.layout2.addWidget(self.saveAsButton)
        self.layout2.addWidget(self.elecTrodeLabel)
        self.layout2.addWidget(self.electroNumberInput)
        self.layout2.addWidget(self.electrodePulseTimeLabel)
        self.layout2.addWidget(self.electrodePulseTimeInput)
        self.layout2.addWidget(self.listWidget)
        self.layout1.addWidget(self.chipViewer)
        self.layout1.addLayout(self.layout2)

        self.main.addWidget(self.chipViewerPage)
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.main)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.consoleWindow = QtWidgets.QDockWidget(MainWindow)
        self.consoleWindow.setMinimumSize(QtCore.QSize(109, 111))
        self.consoleWindow.setStyleSheet(" QDockWidget::title{\n"
"background-color: rgb(250, 250, 250);\n"
"}")
        self.consoleWindow.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.consoleWindow.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.consoleWindow.setObjectName("consoleWindow")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setMinimumSize(QtCore.QSize(0, 85))
        self.dockWidgetContents_3.setMaximumSize(QtCore.QSize(16777215, 600))
        self.dockWidgetContents_3.setStyleSheet("")
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.console = customTextBrowser(self.dockWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.console.setFont(font)
        self.console.setObjectName("console")
        self.gridLayout_3.addWidget(self.console, 0, 0, 1, 1)
        self.consoleWindow.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.consoleWindow)

        self.retranslateUi(MainWindow)
        self.main.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.configButton.setText(_translate("MainWindow", "Configuaration"))
        self.viewButton.setText(_translate("MainWindow", "View"))
        self.chipViewButton.setText(_translate("MainWindow", "Chip Viewer"))
        self.label.setText(_translate("MainWindow", "Flame Spectrometer Configuration"))
        self.label_27.setText(_translate("MainWindow", "Strobe Lamp"))
        self.stropeLampOption.setItemText(0, _translate("MainWindow", "OFF"))
        self.stropeLampOption.setItemText(1, _translate("MainWindow", "ON"))
        self.label_28.setText(_translate("MainWindow", "Strobe Lamp Continous Mode"))
        self.stropeLampMode.setItemText(0, _translate("MainWindow", "OFF"))
        self.stropeLampMode.setItemText(1, _translate("MainWindow", "ON"))
        self.label_29.setText(_translate("MainWindow", "Period"))
        self.periodUnit.setItemText(0, _translate("MainWindow", "milliseconds"))
        self.periodUnit.setItemText(1, _translate("MainWindow", "seconds"))
        self.label_25.setText(_translate("MainWindow", "Integration Time"))
        self.integrationTimeUnit.setItemText(0, _translate("MainWindow", "milliseconds"))
        self.integrationTimeUnit.setItemText(1, _translate("MainWindow", "seconds"))
        self.label_26.setText(_translate("MainWindow", "Trigger Mode"))
        self.triggerMode.setItemText(0, _translate("MainWindow", "Normal"))
        self.triggerMode.setItemText(1, _translate("MainWindow", "EXT Hardware Level"))
        self.triggerMode.setItemText(2, _translate("MainWindow", "EXT Synchronization"))
        self.triggerMode.setItemText(3, _translate("MainWindow", "EXT Hardware Edge"))
        self.label_4.setText(_translate("MainWindow", "Droplet and Electrode Configuration"))
        self.label_30.setText(_translate("MainWindow", "Droplet Travel Time"))
        self.dropletTravelTimeUnit.setItemText(0, _translate("MainWindow", "milliseconds"))
        self.dropletTravelTimeUnit.setItemText(1, _translate("MainWindow", "seconds"))
        self.label_31.setText(_translate("MainWindow", "Pulse Time"))
        self.pulseTimeUnit.setItemText(0, _translate("MainWindow", "milliseconds"))
        self.pulseTimeUnit.setItemText(1, _translate("MainWindow", "seconds"))
        self.label_32.setText(_translate("MainWindow", "Number of Droplet"))
        self.numberOfDropletUnit.setItemText(0, _translate("MainWindow", "per milliseconds"))
        self.numberOfDropletUnit.setItemText(1, _translate("MainWindow", "per seconds"))
        self.label_33.setText(_translate("MainWindow", "Sorting Electrode"))
        self.label_2.setText(_translate("MainWindow", "NEMESYS Pump Configuration"))
        self.nemCheckBox.setText(_translate("MainWindow", "Advanced Setting"))
        self.pumpName.setText(_translate("MainWindow", "Pump Name"))
        self.SyringeDiameter.setText(_translate("MainWindow", "Syringe Diameter\n"
"          (mm)"))
        self.SyringeStroke.setText(_translate("MainWindow", "  Syringe Stroke\n"
"         (mm)"))
        self.pumpStatus.setText(_translate("MainWindow", "   Status"))
        self.label_5.setText(_translate("MainWindow", "Select Pump for Calibration: "))
        self.calibrateButton.setText(_translate("MainWindow", "Calibrate"))
        self.pumpConnectButton.setText(_translate("MainWindow", "Connect"))
        self.label_3.setText(_translate("MainWindow", "NEMESYS System Status:"))
        self.label_7.setText(_translate("MainWindow", "Microcontroller Configuration"))
        self.label_34.setText(_translate("MainWindow", "Device:"))
        self.deviceConnectButton.setText(_translate("MainWindow", "Connect"))
        self.sendParamButtom.setText(_translate("MainWindow", "Send Param"))
        self.label_13.setText(_translate("MainWindow", "Camera Configuration"))
        self.label_35.setText(_translate("MainWindow", "Exposure Time"))
        self.dropletTravelTimeUnit_2.setItemText(0, _translate("MainWindow", "milliseconds"))
        self.label_36.setText(_translate("MainWindow", "Width"))
        self.label_39.setText(_translate("MainWindow", "Height"))
        self.frameRate.setText(_translate("MainWindow", "0 ms"))
        self.label_6.setText(_translate("MainWindow", "Detection Range Configuaration"))
        self.label_37.setText(_translate("MainWindow", "                         Minimum"))
        self.label_38.setText(_translate("MainWindow", "        Maximum"))
        self.label_43.setText(_translate("MainWindow", "Wavelength"))
        self.label_42.setText(_translate("MainWindow", "   nm"))
        self.label_41.setText(_translate("MainWindow", "Intensity"))
        self.label_40.setText(_translate("MainWindow", "  RFU"))
        self.label_45.setText(_translate("MainWindow", "    Select Spectrometer"))
        self.pump4Stop.setText(_translate("MainWindow", "Stop"))
        self.pump1Start.setText(_translate("MainWindow", "Start"))
        self.pump4Start.setText(_translate("MainWindow", "Start"))
        self.pump2Stop.setText(_translate("MainWindow", "Stop"))
        self.pump2Start.setText(_translate("MainWindow", "Start"))
        self.pump5Stop.setText(_translate("MainWindow", "Stop"))
        self.label_15.setText(_translate("MainWindow", "Pump Control"))
        self.pump1Name.setPlaceholderText(_translate("MainWindow", "Pump Name: "))
        self.pump3Stop.setText(_translate("MainWindow", "Stop"))
        self.pump5Start.setText(_translate("MainWindow", "Start"))
        self.pump3Start.setText(_translate("MainWindow", "Start"))
        self.pump1Stop.setText(_translate("MainWindow", "Stop"))
        self.label_18.setText(_translate("MainWindow", "uL"))
        self.pump2FlowRate.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "uL"))
        self.pump5FlowRate.setText(_translate("MainWindow", "0"))
        self.pump3FlowRate.setText(_translate("MainWindow", "0"))
        self.pump4FlowRate.setText(_translate("MainWindow", "0"))
        self.label_22.setText(_translate("MainWindow", "uL"))
        self.label_16.setText(_translate("MainWindow", "Flow Rate"))
        self.label_21.setText(_translate("MainWindow", "uL"))
        self.label_20.setText(_translate("MainWindow", "uL"))
        self.label_44.setText(_translate("MainWindow", "uL/s"))
        self.label_24.setText(_translate("MainWindow", "Flow Rate"))
        self.label_17.setText(_translate("MainWindow", "Flow Rate"))
        self.label_23.setText(_translate("MainWindow", "Flow Rate"))
        self.label_47.setText(_translate("MainWindow", "uL/s"))
        self.label_48.setText(_translate("MainWindow", "uL/s"))
        self.label_46.setText(_translate("MainWindow", "uL/s"))
        self.label_49.setText(_translate("MainWindow", "uL/s"))
        self.label_50.setText(_translate("MainWindow", "Pump 4"))
        self.label_10.setText(_translate("MainWindow", "Pump 3"))
        self.label_8.setText(_translate("MainWindow", "Pump 1"))
        self.label_9.setText(_translate("MainWindow", "Pump 2"))
        self.label_12.setText(_translate("MainWindow", "Pump 5"))
        self.pump1FlowRate.setText(_translate("MainWindow", "0"))
        self.pump2Name.setPlaceholderText(_translate("MainWindow", "Pump Name: "))
        self.pump5Name.setPlaceholderText(_translate("MainWindow", "Pump Name: "))
        self.pump4Name.setPlaceholderText(_translate("MainWindow", "Pump Name: "))
        self.pump3Name.setPlaceholderText(_translate("MainWindow", "Pump Name: "))
        self.label_14.setText(_translate("MainWindow", "Flow Rate"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.console.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
from customWidgets.customGraphicView import customGraphicView
from customWidgets.customTextBrowser import customTextBrowser
from customWidgets.lineEdit import customLineEdit
from pyqtgraph import PlotWidget
import Icon_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
